/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cadd42d3e3a57575017471b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ProcessingService } from '../../services/processing.service';
// Import Models
import { Processing } from '../../domain/sdk4rad_db/processing';
import { Phase } from '../../domain/sdk4rad_db/phase';
import { Article } from '../../domain/sdk4rad_db/article';
import { Schedule } from '../../domain/sdk4rad_db/schedule';

// START - USED SERVICES
/**
* ProcessingService.create
*	@description CRUD ACTION create
*
* ProcessingService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* ProcessingService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Processing
 */
@Component({
    selector: 'app-processing-edit',
    templateUrl: 'processing-edit.component.html',
    styleUrls: ['processing-edit.component.css']
})
export class ProcessingEditComponent implements OnInit {
    item: Processing;
    listPhase: Phase[];
    listProcessing: Processing[];
    listProcessing: Processing[];
    externalArticle: Article[];
    externalSchedule: Schedule[];
    model: Processing;
    formValid: Boolean;

    constructor(
    private processingService: ProcessingService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Processing();
        this.externalArticle = [];
        this.externalSchedule = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.processingService.get(id).subscribe(item => this.item = item);
                this.articleService.findByProcessing(id).subscribe(list => this.externalArticle = list);
                this.scheduleService.findByProcessing(id).subscribe(list => this.externalSchedule = list);
            }
            // Get relations
            this.phaseService.list().subscribe(list => this.listPhase = list);
        });
    }

    /**
     * Check if an Phase is in  phase
     *
     * @param {string} id Id of Phase to search
     * @returns {boolean} True if it is found
     */
    containPhase(id: string): boolean {
        if (!this.item.phase) return false;
        return this.item.phase.indexOf(id) !== -1;
    }

    /**
     * Add Phase from Processing
     *
     * @param {string} id Id of Phase to add in this.item.phase array
     */
    addPhase(id: string) {
        if (!this.item.phase)
            this.item.phase = [];
        this.item.phase.push(id);
    }

    /**
     * Remove an Phase from a Processing
     *
     * @param {number} index Index of Phase in this.item.phase array
     */
    removePhase(index: number) {
        this.item.phase.splice(index, 1);
    }

    /**
     * Save Processing
     *
     * @param {boolean} formValid Form validity check
     * @param Processing item Processing to save
     */
    save(formValid: boolean, item: Processing): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.processingService.update(item).subscribe(data => this.goBack());
            } else {
                this.processingService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



