/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cadd42d3e3a57575017471b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { ScheduleService } from '../../services/schedule.service';
import { ProcessingService } from '../../services/processing.service';
// Import Models
import { Schedule } from '../../domain/sdk4rad_db/schedule';
import { Processing } from '../../domain/sdk4rad_db/processing';

// START - USED SERVICES
/**
* ScheduleService.create
*	@description CRUD ACTION create
*
* ScheduleService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* ProcessingService.list
*	@description CRUD ACTION list
*
* ScheduleService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Schedule
 */
@Component({
    selector: 'app-schedule-edit',
    templateUrl: 'schedule-edit.component.html',
    styleUrls: ['schedule-edit.component.css']
})
export class ScheduleEditComponent implements OnInit {
    item: Schedule;
    listProcessing: Processing[];
    model: Schedule;
    formValid: Boolean;

    constructor(
    private scheduleService: ScheduleService,
    private processingService: ProcessingService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Schedule();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.scheduleService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
            this.processingService.list().subscribe(list => this.listProcessing = list);
        });
    }


    /**
     * Save Schedule
     *
     * @param {boolean} formValid Form validity check
     * @param Schedule item Schedule to save
     */
    save(formValid: boolean, item: Schedule): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.scheduleService.update(item).subscribe(data => this.goBack());
            } else {
                this.scheduleService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



