/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cadd42d3e3a57575017471b
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ScheduleService } from '../../services/schedule.service';
// Import Models
import { Schedule } from '../../domain/sdk4rad_db/schedule';

// START - USED SERVICES
/**
* ScheduleService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* ScheduleService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Schedule
 * @class ScheduleListComponent
 */
@Component({
    selector: 'app-schedule-list',
    templateUrl: './schedule-list.component.html',
    styleUrls: ['./schedule-list.component.css']
})
export class ScheduleListComponent implements OnInit {
    list: Schedule[];
    search: any = {};
    idSelected: string;
    constructor(
        private scheduleService: ScheduleService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.scheduleService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Schedule to remove
     *
     * @param {string} id Id of the Schedule to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Schedule
     */
    deleteItem() {
        this.scheduleService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
