/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cadd42d3e3a57575017471b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CostumerService } from '../../services/costumer.service';
// Import Models
import { Costumer } from '../../domain/sdk4rad_db/costumer';

// START - USED SERVICES
/**
* CostumerService.create
*	@description CRUD ACTION create
*
* CostumerService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id 
*
* CostumerService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Costumer
 */
@Component({
    selector: 'app-costumer-edit',
    templateUrl: 'costumer-edit.component.html',
    styleUrls: ['costumer-edit.component.css']
})
export class CostumerEditComponent implements OnInit {
    item: Costumer;
    model: Costumer;
    formValid: Boolean;

    constructor(
    private costumerService: CostumerService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Costumer();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.costumerService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save Costumer
     *
     * @param {boolean} formValid Form validity check
     * @param Costumer item Costumer to save
     */
    save(formValid: boolean, item: Costumer): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.costumerService.update(item).subscribe(data => this.goBack());
            } else {
                this.costumerService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



