/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cadd42d3e3a57575017471b
*
* You will get 10% discount for each one of your friends
* 
*/
// DEPENDENCIES
import { NgModule } from '@angular/core';
import { CanActivate, RouterModule, Routes } from '@angular/router';

/* START MY VIEWS IMPORT */
// Do not edit this comment content, it will be overwritten in next Skaffolder generation
import { HomeComponent} from './pages/home/home.component';
import { ArticleEditComponent} from './pages/article-edit/article-edit.component';
import { ArticleListComponent} from './pages/article-list/article-list.component';
import { CostumerEditComponent} from './pages/costumer-edit/costumer-edit.component';
import { CostumerListComponent} from './pages/costumer-list/costumer-list.component';
import { ProcessingEditComponent} from './pages/processing-edit/processing-edit.component';
import { ProcessingListComponent} from './pages/processing-list/processing-list.component';
import { ScheduleEditComponent} from './pages/schedule-edit/schedule-edit.component';
import { ScheduleListComponent} from './pages/schedule-list/schedule-list.component';
import { UserEditComponent} from './pages/user-edit/user-edit.component';
import { UserListComponent} from './pages/user-list/user-list.component';

/* END MY VIEWS IMPORT */

// SECURITY
import { LoginComponent } from './pages/login/login.component';
import { ManageUserEditComponent } from './security/manage-user/edit-user/manage-user-edit.component';
import { ManageUserListComponent } from './security/manage-user/list-user/manage-user-list.component';
import { ProfileComponent } from './security/profile/profile.component';
import { AuthGuard } from './security/auth.guard';

/**
 * WEB APP ROUTES
 */
const routes: Routes = [
    { path: '', redirectTo: '/home', pathMatch: 'full'  },

    /* START MY VIEWS */

    { path: 'articles/:id',  loadChildren: './pages/article-edit/article-edit.module#ArticleEditModule' , canActivate: [AuthGuard] },
    { path: 'articles',  loadChildren: './pages/article-list/article-list.module#ArticleListModule' , canActivate: [AuthGuard] },
    { path: 'costumers/:id',  loadChildren: './pages/costumer-edit/costumer-edit.module#CostumerEditModule' , canActivate: [AuthGuard] },
    { path: 'costumers',  loadChildren: './pages/costumer-list/costumer-list.module#CostumerListModule' , canActivate: [AuthGuard] },
    { path: 'home',  loadChildren: './pages/home/home.module#HomeModule' , canActivate: [AuthGuard] },
    { path: 'processings/:id',  loadChildren: './pages/processing-edit/processing-edit.module#ProcessingEditModule' , canActivate: [AuthGuard] },
    { path: 'processings',  loadChildren: './pages/processing-list/processing-list.module#ProcessingListModule' , canActivate: [AuthGuard] },
    { path: 'schedules/:id',  loadChildren: './pages/schedule-edit/schedule-edit.module#ScheduleEditModule' , canActivate: [AuthGuard] },
    { path: 'schedules',  loadChildren: './pages/schedule-list/schedule-list.module#ScheduleListModule' , canActivate: [AuthGuard] },
    { path: 'users/:id',  loadChildren: './pages/user-edit/user-edit.module#UserEditModule' , canActivate: [AuthGuard] },
    { path: 'users',  loadChildren: './pages/user-list/user-list.module#UserListModule' , canActivate: [AuthGuard] },

 /* END MY VIEWS */

    // SECURITY
    { path: 'manage-users',  loadChildren: './security/manage-user/list-user/manage-user-list.module#ManageUserListModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'manage-users/:id',  loadChildren: './security/manage-user/edit-user/manage-user-edit.module#ManageUserEditModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'profile',  loadChildren: './security/profile/profile.module#ProfileModule', canActivate: [AuthGuard] },
    { path: 'login', loadChildren: './pages/login/login.module#LoginModule'}
];

/**
 * ROUTING MODULE
 */
@NgModule({
    imports: [ RouterModule.forRoot(routes) ],
    exports: [ RouterModule ]
})

export class AppRoutingModule {}
